server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexlet
    username: sa
    password: sa
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
